name: github-actions

on:
 
  push:
    branches: github-actions 

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: secrets.AWS_ACCESS_KEY_ID
        aws-secret-access-key: secrets.AWS_SECRET_ACCESS_KEY
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: 629388610155.dkr.ecr.us-east-1.amazonaws.com/hello-world-python2
        ECR_REPOSITORY: hello-world-python2
        IMAGE_TAG: hello-world-python2_image
      run: |
        docker build -t 629388610155.dkr.ecr.us-east-1.amazonaws.com/hello-world-python2:latest .
        docker push -u 629388610155.dkr.ecr.us-east-1.amazonaws.com/hello-world-python2:latest