name: github-actions

on:
 workflow_dispatch:
 push:
    branches: main
    
jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registries: 629388610155
        mask-password: "true"

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: hello-world-python2
        IMAGE_TAG: latest
      run: |
        docker build . -t 629388610155.dkr.ecr.us-east-1.amazonaws.com/hello-world-python2/hello-world-python2:latest
        docker push 629388610155.dkr.ecr.us-east-1.amazonaws.com/hello-world-python2/hello-world-python2:latest
        echo "IMAGE latest is pushed to 629388610155.dkr.ecr.us-east-1.amazonaws.com/hello-world-python2/hello-world-python2
          echo "image_tag=latest 
          echo "629388610155.dkr.ecr.us-east-1.amazonaws.com/hello-world-python2/hello-world-python2:latest"
